# Generated by Django 5.0.2 on 2024-03-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_main_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='learning_modules/')),
                ('sub_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_modules', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PowerPointPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='powerpoint_presentations/')),
                ('sub_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerpoint_presentations', to='courses.course')),
            ],
        ),
    ]
